version: "3.9"
services:
  web:
    build: web/
    image: ksgi/geocoder-platform-web:latest
    volumes:
      - ./app:/code/app
    ports:
      - "7001:8000"
    depends_on:
      - "db"
    container_name: geocoder-platform-web
  db:
    build: db/
    image: ksgi/geocoder-platform-db:latest
    volumes:
      - gisdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=census
      - POSTGRES_PASSWORD=census
    shm_size: 1gb
    container_name: geocoder-platform-db
volumes:
  gisdata: